- name: "good-first-issue"
  color: "FFFFFF"
  description: "[Welcome] Perfect for new contributors."
  from_name: "good-first-issue"
- name: "dependencies"
  color: "E6E6E6"
  description: "[Update] Pull requests that update a dependency file."
  from_name: "dependencies"
- name: "javascript"
  color: "E6E6E6"
  description: "[Update] Pull requests that update Javascript code."
  from_name: "javascript"
- name: "python"
  color: "E6E6E6"
  description: "[Update] Pull requests that update Python code."
  from_name: "python"
- name: "bug"
  color: "FB3640"
  description: "[Problem] Something isn’t working or looking right."
  from_name: "bug"
- name: "vulnerability"
  color: "FB3640"
  description: "[Problem] Security vulnerability report only."
  from_name: "vulnerability"
- name: "question"
  color: "FB3640"
  description: "[Problem] Further help and/or information is required."
  from_name: "question"
- name: "feature"
  color: "AE79FF"
  description: "[Improvement] New feature request."
  from_name: "feature"
- name: "enhancement"
  color: "AE79FF"
  description: "[Improvement] Enhancement request."
  from_name: "enhancement"
- name: "test"
  color: "AE79FF"
  description: "[Improvement] Anything related to testing or tests."
  from_name: "test"
- name: "deployment"
  color: "AE79FF"
  description: "[Improvement] Anything relating to deployment."
  from_name: "deployment"
- name: "major"
  color: "00DBFF"
  description: "[Release] Major release."
  from_name: "major"
- name: "minor"
  color: "00DBFF"
  description: "[Release] Minor release."
  from_name: "minor"
- name: "patch"
  color: "00DBFF"
  description: "[Release] Patch release."
  from_name: "patch"
- name: "wont-fix"
  color: "1C1C1C"
  description: "[Inactive] This will not be worked on."
  from_name: "wont-fix"
- name: "duplicate"
  color: "1C1C1C"
  description: "[Inactive] This issue or pull request already exists."
  from_name: "duplicate"
