# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: upload

  # A short description of the repository that will show up on GitHub
  description: gliff.ai UPLOAD – a component for allowing the upload of a variety of image files, including multidimensional TIFFs, for the purposes for machine learning development.
  
  # A comma-separated list of topics to set on the repository
  topics: contributions-welcome, image-upload, machine-learning, MLOps, artificial-intelligence, dataops, gliff-ai

  # Updates the default branch for this repository.
  default_branch: main

# Labels: define labels for Issues and Pull Requests
labels:
  - name: good-first-issue
    color: '#FFFFFF'
    description: [Welcome] Perfect for new contributors.
    
  - name: dependencies
    new_name: dependencies
    color: '#E6E6E6'
    description: [Update] Pull requests that update a dependency file.

  - name: javascript
    new_name: javascript
    color: '#E6E6E6'
    description: [Update] Pull requests that update Javascript code.
    
  - name: python
    color: '#E6E6E6'
    description: [Update] Pull requests that update Python code.

  - name: bug
    new_name: bug
    color: '#FB3640'
    description: [Problem] Something isn’t working or looking right.

  - name: vulnerability
    color: '#FB3640'
    description: [Problem] Security vulnerability report only.
    
  - name: question
    new_name: help
    color: '#FB3640'
    description: [Problem] Further help and/or information is required.
    
  - name: feature
    color: '#AE79FF'
    description: [Improvement] New feature request.

  - name: enhancement
    new_name: enhancement
    color: '#AE79FF'
    description: [Improvement] Enhancement request.

  - name: test
    new_name: test
    color: '#AE79FF'
    description: [Improvement] Anything related to testing or tests.
    
  - name: deployment
    new_name: deployment
    color: '#AE79FF'
    description: [Improvement] Anything relating to deployment.
    
  - name: major
    new_name: major
    color: '#00DBFF'
    description: [Release] Major release.

  - name: minor
    new_name: minor
    color: '#00DBFF'
    description: [Release] Minor release.
    
  - name: patch
    new_name: patch
    color: '#00DBFF'
    description: [Release] Patch release.
    
  - name: wontfix
    new_name: wont-fix
    color: '#1C1C1C'
    description: [Inactive] This will not be worked on.
    
  - name: duplicate
    new_name: duplicate
    color: '#1C1C1C'
    description: [Inactive] This issue or pull request already exists.
