name: Build & Publish
on:
  release:
    types:
      - created

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
          scope: "@gliff-ai"
      - name: Setup dependencies
      - run: npm i
      - name: Build
        run: npm run build
      - name: Publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
